#utils_path: '{{ inventory_dir | dirname }}'

aggregator_configmap_link: https://raw.githubusercontent.com/shiveshabhishek/efk-stack/F-cluster-configs/fluentd-aggregator-config.yaml

agg_cnfg_yaml_alias: fluentd-aggregator-config.yaml

aggregator_deployment_link: https://raw.githubusercontent.com/shiveshabhishek/efk-stack/master/fluentd/fluentd-aggregator-deployment.yaml

agg_dpl_yaml_alias: fluentd-aggregator-deployment.yaml

aggregator_services_link: https://raw.githubusercontent.com/shiveshabhishek/efk-stack/master/fluentd/fluentd-aggregator-svc.yaml

agg_svc_yaml_alias: fluentd-aggregator-svc.yaml

forwarder_configmap_link: https://raw.githubusercontent.com/shiveshabhishek/efk-stack/F-cluster-configs/fluentd-forwarder-config.yaml

fwd_cnfg_yaml_alias: fluentd-forwarder-config.yaml

forwarder_daemonset_link: https://raw.githubusercontent.com/shiveshabhishek/efk-stack/master/fluentd/fluentd-forwarder-daemonset.yaml

fwd_dmn_yaml_alias: fluentd-forwarder-daemonset.yaml

namespace: logging

commit_id: "{{ commit_id }}"

pipeline_id: "{{ pipeline_id }}"
