kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-aggregator
  namespace: logging
  labels:
    k8s-app: fluentd-aggregator
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>

  output.conf: |-
    # Input
    <source>
      @type forward
      port 24224
    </source>
    
    # Output
    <match **>
      @id elasticsearch
      @type elasticsearch
      # @log_level info
      logstash_format true
      include_timestamp true
      logstash_prefix cluster-logs
      # !Important(required to connect with elasticsearch with https request)
      scheme https
      ssl_version TLSv1_2
      include_tag_key true
      hosts https://e2elogs.test.openebs.io:443/es/
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer.aggregator
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
